name: CI - Syntax check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python syntax (compileall)
        run: |
          python -m compileall -q .
